name: update-non-snapshots
on:
  # will send emails to last editor of this cron syntax (distroless-bot)
  schedule:
    - cron: "35 20 * * *"
  # allow this workflow to be manually run
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v6

      - name: Update non-snapshots
        run: ./knife update-non-snapshots

      - name: Check for changes
        run: |
          git status
          if [[ $(git status --porcelain) ]]; then 
            echo "DISTROLESS_DIFF=true" >> "$GITHUB_ENV"
          else
            echo "No changes detected"
            exit 0
          fi

      - name: Run update lockfile
        if: env.DISTROLESS_DIFF
        run: bazel mod deps --lockfile_mode=update

      - name: Create commits
        if: env.DISTROLESS_DIFF
        id: create-commits
        run: |
          git checkout -b update-non-snapshots

          # Set identity.
          git config --global user.email "distroless-bot@google.com"
          git config --global user.name "Distroless Bot"

          # Commit changes
          git add .
          git commit -s -m "Bumping non-snapshot packages to latest stable versions"
          git push --force origin HEAD

      - name: Create Pull Request
        if: env.DISTROLESS_DIFF
        env:
          GH_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        run: |
          BODY_FILE=$(mktemp)
          printf "Bumping non-snapshot packages to latest stable version\n" >> $BODY_FILE
          if ! OUTPUT=$(gh pr create -B main -H update-non-snapshots -t "Bumping packages to latest stable versions" --body-file "$BODY_FILE" 2>&1) ; then
            echo $OUTPUT
            if [[ "${OUTPUT}" =~ "already exists" ]]; then
              echo "PR already exists and it was updated. Ending successfully";
              exit 0;
            else
              exit 1;
            fi
          fi
