name: update-snapshots
on:
  # will send emails to last editor of this cron syntax
  schedule:
    - cron:  '35 8 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3
        

    - name: Set up Go 1.16.x
      uses: actions/setup-go@v3
      with:
        go-version: 1.16.x
      id: go

    - name: Run update script
      run: ./updateWorkspaceSnapshots.sh
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@b4d51739f96fca8047ad065eccef63442d8e99f7 # v4.1.3
      with:
        token: ${{ secrets.ACTIONS_TOKEN }}
        commit-message: "Bumping packages to latest stable versions"
        author: "Distroless Bot <distroless-bot@google.com>"
        title: "Bumping packages to latest stable versions"
        body: "Bumping packages to latest stable versions"
        branch: "update-snapshots"
